---
- hosts: all
  become: true
  
  name: install gitab
  tasks:
  - name: Install python3-pip
    ansible.builtin.apt:
      pkg:
        - python3-pip

  - name: Install req
    ansible.builtin.pip:
      name: "{{ item }}"
      umask: "0022"
    with_items:
      - docker
      - docker-compose
      
  - name: Create dirs
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
    with_items:
      - /srv/gitlab/config
      - /srv/gitlab/data
      - /srv/gitlab/logs

  - name: copy template file
    ansible.builtin.template:
      src: gitlab.yml.j2
      dest: /srv/gitlab/docker-compose.yml
      mode: 0755
      
  - name: Docker-compose up
    community.docker.docker_compose:
      project_src: /srv/gitlab/
      state: present