---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{  template "ui.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - secretName: letsencrypt
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "ui.fullname" . }}
            port:
              number: {{ .Values.service.externalPort }}
